name: 'Shopify Theme Dupliate'
description: 'Sync Shopify Theme JSONs'
author: 'devil1991'
inputs:
  store:
    required: true
    description: 'Store'
  env:
    required: true
    description: 'Env Staging / Production used as Prefix'
  theme:
    required: false
    description: 'Target Theme ID'
runs:
  main: 'dist/index.js'
  using: 'node20'
